INSERT INTO dbo.Pet (PetName, DateOfBirth, Bread, DogOwner, Email) VALUES
('Vanessa', '2008-11-19', 'Cocker Spaniel', 'Vincent Butcher', 'evanszoe@example.com'),
('Lisa', '2020-04-22', 'Cocker Spaniel', 'Ms Marie Smith', 'katieali@example.org'),
('Ben', '2019-04-11', 'Beagle', 'Ms Pauline Hunt', 'browntony@example.net'),
('Josh', '2008-10-14', 'Golden Retriever', 'Molly Marsh', 'bethansmith@example.org'),
('Josh', '2018-02-28', 'Labrador Retriever', 'Lynn Richardson', 'frussell@example.org'),
('Abigail', '2023-02-20', 'French Bulldog', 'Kirsty Allen', 'carlrowe@example.net'),
('Anthony', '2022-04-06', 'Bulldog', 'Judith Walker', 'kirsty35@example.net'),
('Karl', '2016-10-10', 'Rottweiler', 'Katie Richards', 'clarkaaron@example.com'),
('Connor', '2020-06-01', 'Rottweiler', 'Dr Christian Collins', 'barberstacey@example.org'),
('Samantha', '2008-10-31', 'Golden Retriever', 'Joan Stanley', 'john14@example.com'),
('Joanna', '2023-02-09', 'Beagle', 'Bethan George', 'grahamalex@example.org'),
('Julia', '2024-02-01', 'Labrador Retriever', 'Dr Shaun Joyce', 'baileymarilyn@example.com'),
('Scott', '2023-11-27', 'Rottweiler', 'Charles Walton-Short', 'lcartwright@example.net'),
('Douglas', '2018-03-25', 'Rottweiler', 'Mr Max Dawson', 'dharvey@example.org'),
('Chloe', '2018-08-30', 'German Shepherd', 'Diana Brooks', 'zoe36@example.com'),
('Jayne', '2011-07-10', 'Poodle', 'Mrs Kimberley Singh', 'keithdavies@example.net'),
('Kimberley', '2020-08-13', 'Cocker Spaniel', 'Peter Gibbons', 'ellislindsey@example.org'),
('Shannon', '2009-08-19', 'Golden Retriever', 'Teresa Brown', 'elliepearce@example.net'),
('Geoffrey', '2014-06-02', 'Poodle', 'Russell O''Brien', 'vanessa64@example.com'),
('Joyce', '2013-08-02', 'Yorkshire Terrier', 'Wayne Tomlinson', 'amandalaw@example.net'),
('Marc', '2011-08-12', 'Cocker Spaniel', 'Kirsty Martin', 'nicole25@example.net'),
('Victor', '2022-12-04', 'Yorkshire Terrier', 'Gregory Byrne', 'arthurlee@example.com'),
('Joe', '2018-03-07', 'Rottweiler', 'Damian Bruce', 'olivermarian@example.com'),
('Clive', '2015-07-11', 'French Bulldog', 'Jacqueline Young', 'samanthafrancis@example.com'),
('Jayne', '2020-05-17', 'French Bulldog', 'Mrs Rachael Mitchell', 'brendajames@example.com'),
('Keith', '2014-10-13', 'Beagle', 'Dawn Singh', 'graham97@example.net'),
('Geoffrey', '2017-10-30', 'Yorkshire Terrier', 'Ms Susan Hawkins', 'nelsonkarl@example.net'),
('Beth', '2019-08-21', 'Rottweiler', 'Wayne Wilson', 'wturnbull@example.org'),
('Brenda', '2009-09-11', 'Yorkshire Terrier', 'Ms Sylvia Reynolds', 'taylorsally@example.com'),
('Eric', '2011-11-18', 'French Bulldog', 'Natasha Hope', 'martindeborah@example.net'),
('Mandy', '2020-08-18', 'Yorkshire Terrier', 'Mr Abdul Williams', 'juliepotter@example.net'),
('Mitchell', '2012-06-12', 'French Bulldog', 'Maureen Osborne', 'sclarke@example.com'),
('Molly', '2011-10-01', 'Bulldog', 'Rhys Bradley', 'websterkevin@example.org'),
('Samantha', '2013-03-04', 'Bulldog', 'Ms Teresa Lee', 'brownfrancesca@example.com'),
('Garry', '2015-10-02', 'Cocker Spaniel', 'Mr Mitchell Ward', 'annettelewis@example.net'),
('Chelsea', '2015-08-18', 'Cocker Spaniel', 'Ms Julie Thomas', 'janetmills@example.org'),
('Julie', '2019-02-10', 'Cocker Spaniel', 'George Brooks-Thomas', 'janethutchinson@example.net'),
('Jeremy', '2012-03-13', 'Rottweiler', 'Daniel Brown', 'leon26@example.net'),
('Alice', '2015-11-28', 'Beagle', 'Kieran Parker', 'aimee06@example.org'),
('Donna', '2011-12-20', 'Cocker Spaniel', 'Jasmine Holland', 'gavin30@example.com'),
('Bryan', '2021-07-17', 'Rottweiler', 'Timothy Nash', 'julieslater@example.com'),
('Linda', '2011-11-11', 'German Shepherd', 'Marian Fuller', 'garrycunningham@example.org'),
('John', '2017-06-23', 'German Shepherd', 'Amber Shaw-Jenkins', 'martinkimberley@example.org'),
('Georgia', '2012-01-18', 'Cocker Spaniel', 'Mr Patrick Morris', 'michelleodonnell@example.com'),
('Derek', '2015-12-17', 'Poodle', 'Mrs Kirsty Smith', 'barbaracoleman@example.org'),
('Victor', '2009-12-08', 'Golden Retriever', 'Stanley Burgess-Murphy', 'sandra47@example.net'),
('Catherine', '2011-08-22', 'Beagle', 'Charles King', 'hazelnorth@example.org'),
('Albert', '2015-01-09', 'Cocker Spaniel', 'Abdul West-Watson', 'hussainstephen@example.com'),
('Melissa', '2018-10-30', 'Golden Retriever', 'Dr Pauline Wade', 'znicholls@example.net'),
('Howard', '2017-11-08', 'Labrador Retriever', 'Aimee Buckley', 'obennett@example.com'),
('Ricky', '2016-09-10', 'Labrador Retriever', 'Cameron Williams', 'yvonne32@example.net'),
('Ellie', '2010-05-21', 'Rottweiler', 'Teresa Taylor', 'ocarroll@example.org'),
('Ryan', '2022-04-27', 'French Bulldog', 'Pauline Jackson-Abbott', 'zrogers@example.org'),
('Deborah', '2015-04-28', 'Bulldog', 'Mrs Valerie Parker', 'smithwayne@example.org'),
('Hilary', '2024-03-10', 'Yorkshire Terrier', 'Dr Kim Jarvis', 'nwarner@example.net'),
('Gordon', '2023-04-28', 'Poodle', 'Gary Turner', 'mariannorth@example.org'),
('Chloe', '2023-04-03', 'Rottweiler', 'Joseph Atkinson', 'pauline52@example.com'),
('Darren', '2016-07-30', 'Rottweiler', 'Shaun Hill', 'mhussain@example.org'),
('Claire', '2012-09-09', 'Golden Retriever', 'Leigh Kelly', 'djohnson@example.com'),
('Annette', '2022-04-12', 'German Shepherd', 'Fiona King', 'cnorman@example.net'),
('Paul', '2019-03-22', 'Beagle', 'Max Bird', 'qgriffin@example.org'),
('Bruce', '2023-06-07', 'Cocker Spaniel', 'Ronald Khan', 'antonyreynolds@example.net'),
('Tony', '2017-11-08', 'Rottweiler', 'Miss Gail Howard', 'fsutton@example.com'),
('Damian', '2010-07-30', 'Cocker Spaniel', 'Jean Ford-Parker', 'victoriasmith@example.org'),
('Donald', '2015-12-27', 'Labrador Retriever', 'John Holt', 'samantha72@example.com'),
('Georgia', '2019-09-04', 'Yorkshire Terrier', 'Cameron Gill', 'zwalker@example.org'),
('Denis', '2010-09-10', 'Rottweiler', 'Mr Liam Smith', 'tcook@example.org'),
('Kate', '2011-08-03', 'French Bulldog', 'Deborah Tucker', 'kimmoore@example.net'),
('Mathew', '2009-03-24', 'Yorkshire Terrier', 'Mrs Rachel Taylor', 'clivemanning@example.org'),
('Gregory', '2018-07-02', 'Cocker Spaniel', 'Marilyn Smith', 'janewalton@example.net'),
('Anthony', '2011-04-21', 'Beagle', 'Reece Bradley', 'codonnell@example.com'),
('Pauline', '2022-04-25', 'Golden Retriever', 'Kenneth Griffiths-Morgan', 'craigsmith@example.com'),
('Joanne', '2011-12-14', 'Poodle', 'Stanley Wilkins', 'pughjason@example.com'),
('Craig', '2011-07-19', 'Golden Retriever', 'Richard Bradshaw', 'ricky65@example.net'),
('Olivia', '2010-11-12', 'Labrador Retriever', 'Gordon James', 'catherine83@example.com'),
('Margaret', '2011-11-18', 'French Bulldog', 'Benjamin Whitehead', 'rickytaylor@example.org'),
('Carolyn', '2022-03-31', 'Beagle', 'Mr Jason Armstrong', 'greenkathryn@example.com'),
('Gerald', '2019-11-28', 'Rottweiler', 'Ms Leanne Burrows', 'powelljoseph@example.net'),
('Daniel', '2013-05-23', 'Bulldog', 'Dr Catherine James', 'samueldixon@example.com'),
('Rosemary', '2017-06-06', 'French Bulldog', 'Norman Davey-Saunders', 'lambertnathan@example.org'),
('Carol', '2021-08-17', 'Golden Retriever', 'Roger Wilkinson', 'allenlesley@example.com'),
('Anne', '2012-04-26', 'Cocker Spaniel', 'Joshua Roberts', 'mpayne@example.org'),
('Trevor', '2014-05-18', 'German Shepherd', 'Dr Tony Lewis', 'pmoran@example.net'),
('Amber', '2009-08-23', 'Cocker Spaniel', 'Hayley Lucas', 'joshturner@example.net'),
('Brenda', '2011-11-05', 'German Shepherd', 'Miss Tracey Jones', 'juliedean@example.com'),
('Mitchell', '2023-09-18', 'Cocker Spaniel', 'Mrs Melanie Evans', 'tali@example.org'),
('Leonard', '2023-11-03', 'Poodle', 'Natasha Green', 'gordondavies@example.com'),
('Bradley', '2020-05-05', 'Beagle', 'Janice Wright', 'pthomas@example.net'),
('Amanda', '2022-03-26', 'Beagle', 'Rosemary Chambers-Fletcher', 'damienford@example.org'),
('John', '2021-09-22', 'Golden Retriever', 'Mr Gerald Khan', 'andrewsbenjamin@example.net'),
('Sam', '2023-01-06', 'German Shepherd', 'Alexander Wong', 'arthur53@example.com'),
('Samantha', '2014-12-05', 'Poodle', 'Frank Hunt', 'hsims@example.com'),
('Jean', '2016-01-29', 'Labrador Retriever', 'Yvonne Mason', 'tstevens@example.org'),
('Adrian', '2020-06-03', 'Cocker Spaniel', 'Sally McKenzie', 'scott52@example.org'),
('Judith', '2023-03-31', 'Cocker Spaniel', 'Chloe Wright', 'bowenhazel@example.net'),
('Nathan', '2015-12-28', 'Labrador Retriever', 'Ian Chamberlain', 'nthompson@example.com'),
('Paula', '2008-11-04', 'Cocker Spaniel', 'Dr Oliver Vaughan', 'vsheppard@example.org'),
('Lucy', '2017-09-17', 'Golden Retriever', 'Scott Willis', 'xscott@example.net'),
('Rosemary', '2018-12-30', 'Rottweiler', 'Mitchell Nixon', 'jeanfisher@example.org'),
('Shirley', '2011-05-19', 'German Shepherd', 'Dr Justin Moore', 'harrisjoanna@example.net');